### ISSUE TITLE
Menu visibility issues

### ISSUE THREAD

**Issue by michaelsills** [Alexa-McDaniel/Bev-s-Bday_AboutUs#2]
There are some significant visibility (and likely ADA) issues with the menu visibility as indicated in the screenshots.

![image](https://user-images.githubusercontent.com/61249749/105732404-65597e00-5efe-11eb-9049-cf0f79d02934.png)

![image](https://user-images.githubusercontent.com/61249749/105732537-8de17800-5efe-11eb-8810-a41992c273a2.png)

I discussed this briefly with Alexa and she agreed that this needs some further discussion.

**Comment by BrianBenninger** [comment]
After speaking with @Alexa-McDaniel I have implemented a white box behind the current menu. This is just a temporary fix until we can re-vamp the menu.

**Comment by michaelsills** [comment]
Looking good.  Closing.
