### ISSUE TITLE
Confetti overlapping text

### ISSUE THREAD

**Issue by michaelsills** [Alexa-McDaniel/Bev-s-Bday_AboutUs#3]
The confetti scrolls and overlaps the main text on certain parts of the page.

![image](https://user-images.githubusercontent.com/61249749/105740149-e87ed200-5f06-11eb-8032-b1bc9f9247dc.png)

Mobile:
![File (5)](https://user-images.githubusercontent.com/61249749/105759691-bbd6b480-5f1e-11eb-998b-c941f1dd12bb.jpg)

![File (6)](https://user-images.githubusercontent.com/61249749/105863320-c6488b00-5fbe-11eb-9564-c082b5e2b13c.jpg)

**Comment by BrianBenninger** [comment]
@michaelsills spoke with Mike on this. He is not worried about the overlap on issues 1 and 2 due to the overlap happening so close to the top edge of the screen. 3 is fixed.

**Comment by BrianBenninger** [comment]
With the provision that we will address this overlap later. Possibly during a phase 2?

**Comment by michaelsills** [comment]
The 3rd section is passable.  The confetti passes behind the text now.  It's not ideal, but will be okay in the interim.
