### ISSUE TITLE
Leadership and board member list scrolling - mobile

### ISSUE THREAD

**Issue by michaelsills** [Alexa-McDaniel/Bev-s-Bday_AboutUs#6]
On mobile, the selection of the board members and leadership has an unwieldly interface/scrolling/selection options.  

This is currently in discussion.  Opened for tracking. 

![image](https://user-images.githubusercontent.com/61249749/105755490-58965380-5f19-11eb-8fe3-a5948f3e1f2b.png)

**Comment by Alexa-McDaniel** [comment]
From our discussion, I think we decided that having a "1/10" format might work best for this area

**Comment by BrianBenninger** [comment]
We are now using fractional pagination on both of these blocks.

**Comment by michaelsills** [comment]
This has also been implemented on the county section per discussion with Alexa.  All look good. Closing.
