### ISSUE TITLE
"Menu" changing colors - visibility

### ISSUE THREAD

**Issue by michaelsills** [Alexa-McDaniel/Bev-s-Bday_AboutUs#7]
This is also on desktop when scrolling to some degree but it is harder to see, but it's very obvious on mobile.  In this screenshot, iPhone 10.

Look at the menu in the upper left corner when viewing the video.  It fades in at white when scrolling down (unexpected/wrong color) and then disappears (as expected).  And then when scrolling up, the "MENU" is black (correct?) and then fades to white at the top.

I can't compress the file enough to add it here.  Please let me know when you view this and I will send the attachment.

**Comment by BrianBenninger** [comment]
I believe the white box changes that I put in place for #2 may have fixed this bug as well.

**Comment by michaelsills** [comment]
This is solved by the menu rework mentioned. Closing.
