### ISSUE TITLE
County sort order - mobile

### ISSUE THREAD

**Issue by michaelsills** [Alexa-McDaniel/Bev-s-Bday_AboutUs#8]
http://dev-beverlys-birthday-wp.chemistry.digital/about-test/

When selecting some counties, the sort order changes.  For example, selecting Westmoreland, changes the sort order from Alphabetical to  Washington, and then Allegheny.  I would expect the sort to remain alphabetical for the counties that are not selected.

![Screenshot_20210126-102631](https://user-images.githubusercontent.com/61249749/105878304-e1bb9200-5fce-11eb-85eb-fa96f204c09a.png)

**Comment by BrianBenninger** [comment]
Sort order has been corrected.

**Comment by michaelsills** [comment]
Looks good.  Closing.
