### ISSUE TITLE
Page auto-refreshing on Android

### ISSUE THREAD

**Issue by michaelsills** [Alexa-McDaniel/Bev-s-Bday_AboutUs#9]
When scrolling down the page, the page randomly refreshes with no other interaction.  Simply scrolling seems to trigger it.

This is happening on the Android Pixel and Android tablet (Samsung Tab A). This was recorded behavior for the Tab A.  Both current android devices I have here are doing the same thing.

The video is too big to attach, so I will send direct when you are ready to work on this

**Comment by BrianBenninger** [comment]
@michaelsills I believe I have this corrected. You will need to clear your cache to get the new JS.

**Comment by michaelsills** [comment]
Passing.  No longer refreshing.
